# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(479, 574)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("monki.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 441, 20))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.txtSongs = QtWidgets.QTextEdit(self.centralwidget)
        self.txtSongs.setGeometry(QtCore.QRect(19, 31, 441, 192))
        self.txtSongs.setStyleSheet("border: 1px solid black")
        self.txtSongs.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.txtSongs.setPlaceholderText("")
        self.txtSongs.setObjectName("txtSongs")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(19, 229, 441, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(30, 10, 30, 10)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btImportTxt = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btImportTxt.sizePolicy().hasHeightForWidth())
        self.btImportTxt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        self.btImportTxt.setFont(font)
        self.btImportTxt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btImportTxt.setMouseTracking(True)
        self.btImportTxt.setStyleSheet("background-color: black; color: white; border: 1px solid blue")
        self.btImportTxt.setObjectName("btImportTxt")
        self.horizontalLayout.addWidget(self.btImportTxt)
        self.btDownload = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btDownload.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btDownload.sizePolicy().hasHeightForWidth())
        self.btDownload.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        self.btDownload.setFont(font)
        self.btDownload.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btDownload.setMouseTracking(True)
        self.btDownload.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btDownload.setAutoFillBackground(False)
        self.btDownload.setStyleSheet("background-color: black; color: white; border: 1px solid blue")
        self.btDownload.setCheckable(False)
        self.btDownload.setChecked(False)
        self.btDownload.setAutoRepeat(False)
        self.btDownload.setAutoExclusive(False)
        self.btDownload.setAutoDefault(False)
        self.btDownload.setDefault(False)
        self.btDownload.setFlat(False)
        self.btDownload.setObjectName("btDownload")
        self.horizontalLayout.addWidget(self.btDownload)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(20, 300, 441, 24))
        font = QtGui.QFont()
        font.setBold(True)
        self.progressBar.setFont(font)
        self.progressBar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.progressBar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.progressBar.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.progressBar.setAcceptDrops(False)
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setStyleSheet("QProgressBar\n"
"{\n"
"border: 1px solid black;\n"
"border-radius: 15px;\n"
"color: black;\n"
"}\n"
"QProgressBar::chunk \n"
"{\n"
"background-color: rgb(151, 200, 124);\n"
"border-radius :15px;\n"
"}      ")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 340, 441, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.txtTerminal = QtWidgets.QTextEdit(self.centralwidget)
        self.txtTerminal.setEnabled(True)
        self.txtTerminal.setGeometry(QtCore.QRect(20, 360, 441, 191))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        self.txtTerminal.setFont(font)
        self.txtTerminal.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.txtTerminal.setAutoFillBackground(False)
        self.txtTerminal.setStyleSheet("background-color: gray; border: 1px solid black")
        self.txtTerminal.setInputMethodHints(QtCore.Qt.ImhNone)
        self.txtTerminal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.txtTerminal.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.txtTerminal.setLineWidth(2)
        self.txtTerminal.setMidLineWidth(2)
        self.txtTerminal.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.txtTerminal.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.txtTerminal.setReadOnly(True)
        self.txtTerminal.setMarkdown("")
        self.txtTerminal.setAcceptRichText(True)
        self.txtTerminal.setCursorWidth(1)
        self.txtTerminal.setPlaceholderText("")
        self.txtTerminal.setObjectName("txtTerminal")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MonkeyTube Downloader"))
        self.label.setText(_translate("MainWindow", "ESCREVA ABAIXO OU IMPORTE UM ARQUIVO .TXT"))
        self.txtSongs.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btImportTxt.setText(_translate("MainWindow", "IMPORTAR .TXT"))
        self.btDownload.setText(_translate("MainWindow", "BAIXAR"))
        self.label_2.setText(_translate("MainWindow", "TERMINAL DE SAÍDA"))
        self.txtTerminal.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:italic;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
